Repository kubernetes-sigs/provider-ibmcloud-test-infra, pull requests merged in 2025-04, with the labels that each got.

#19 Code for managing IBM Cloud secret manager
  .github/workflows/secret-manager.yaml
  secret-manager/README.md
  secret-manager/cmd/root.go
  secret-manager/cmd/rotate.go
  secret-manager/go.mod
  secret-manager/go.sum
  secret-manager/internal/pkg/iam/iam.go
  secret-manager/internal/pkg/secretmanager/secretmanager.go
  secret-manager/main.go
Labels: size/XL, approved, cncf-cla: yes, lgtm

#21 code cleanup
  secret-manager/cmd/rotate.go
  secret-manager/go.mod
  secret-manager/go.sum
  secret-manager/internal/pkg/secretmanager/secretmanager.go
Labels: size/M, approved, cncf-cla: yes, lgtm

#24 Error handling
  secret-manager/cmd/rotate.go
Labels: approved, cncf-cla: yes, size/S, lgtm

#22 Add feature-gates to kubelet, apiserver, scheduler, controller
  kubetest2-tf/data/k8s-ansible/roles/install-k8s/templates/kubeadm.yaml.j2
Labels: approved, cncf-cla: yes, size/S, lgtm

#13 Move kubeadm templates from v1beta3 to v1beta4
  kubetest2-tf/data/k8s-ansible/roles/install-k8s/templates/kubeadm.yaml.j2
Labels: size/M, approved, cncf-cla: yes, lgtm

#25 Fix kubeadm config templation
  kubetest2-tf/data/k8s-ansible/roles/install-k8s/templates/kubeadm.yaml.j2
Labels: approved, cncf-cla: yes, size/S, lgtm

#28 Introduce tasks to patch OS with latest updates
  kubetest2-tf/data/k8s-ansible/patch-nodes.yaml
  kubetest2-tf/data/k8s-ansible/roles/reboot-sequentially/tasks/main.yaml
  kubetest2-tf/data/k8s-ansible/roles/update-node-os/tasks/main.yaml
Labels: size/M, approved, cncf-cla: yes, lgtm
