Repository kubernetes-sigs/provider-ibmcloud-test-infra, pull requests merged in 2025-03, with the labels that each got.

#3 Introduce tasks to update nodes with latest available packages
  kubetest2-tf/data/k8s-ansible/install-k8s.yml
  kubetest2-tf/data/k8s-ansible/roles/install-k8s/tasks/main.yml
  kubetest2-tf/data/k8s-ansible/roles/k8s-node/tasks/main.yml
  kubetest2-tf/data/k8s-ansible/roles/k8s-ut/tasks/main.yml
  kubetest2-tf/data/k8s-ansible/roles/runtime/tasks/containerd.yaml
  kubetest2-tf/data/k8s-ansible/roles/runtime/tasks/crio.yaml
  kubetest2-tf/data/k8s-ansible/roles/runtime/tasks/main.yaml
  kubetest2-tf/data/k8s-ansible/roles/update-pkgs/tasks/main.yml
Labels: size/M, approved, cncf-cla: yes, lgtm

#4 Add Makefile recipe for installing kubetest2-tf
  Makefile
  kubetest2-tf/Makefile
  kubetest2-tf/hack/goinstalldir.sh
Labels: size/M, approved, cncf-cla: yes, lgtm

#6 Add github workflow for building the binary
  .github/workflows/go.yaml
Labels: approved, cncf-cla: yes, size/S, lgtm

#10 Add a hack folder to host common scripts used by jobs
  hack/boskos.sh
Labels: size/M, approved, cncf-cla: yes, lgtm

#11 Include CentOS environments for disabling selinux
  kubetest2-tf/data/k8s-ansible/roles/disable-swap-selinux/tasks/main.yml
Labels: approved, cncf-cla: yes, size/XS, lgtm

#12 script to setup terraform on power/x86
  Makefile
  kubetest2-tf/Makefile
  kubetest2-tf/hack/terraform_install.sh
Labels: size/M, approved, cncf-cla: yes, lgtm

#15 Add boskos checkout resources call to hack/boskos.sh
  hack/boskos.sh
Labels: size/M, approved, cncf-cla: yes, lgtm

#17 fix provider paths
  kubetest2-tf/hack/terraform_install.sh
Labels: approved, cncf-cla: yes, size/S, lgtm

#18 Remove errexit disable from boskos checkout
  hack/boskos.sh
Labels: approved, cncf-cla: yes, size/XS, lgtm
